config/routes.rb
Rails.application.routes.draw do

  get 'reports/fetch_report'

  resources :orders


  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'

  resources :users

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/uzel', to:"users#ajax_uzel",          via: 'post'



  resources :sessions, only: [:new, :create, :destroy]


  resources :reports

  match '/report', to:"reports#fetch_report",   via: 'post'

  root 'orders#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_roles
  has_many :roles, through: :users_roles

  before_create :create_remember_token
  before_save { self.email = email.downcase }


  validates :name, presence: true, length: {minimum: 3, maximum: 50}

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with:EMAIL_REGEX}, uniqueness: {case_sensitive: true}


  has_secure_password
  validates :password, length: { minimum: 6 }, unless: :skip_password_validation

  attr_accessor :skip_password_validation

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def is_admin?
    self.roles.first.name == 'admin';
  end

  def is_agent?
    self.roles.first.name == 'agent';
  end

  def is_client?
    self.roles.first.name == 'client';
  end

  def is_guest?
    self.roles.first.name == 'guest';
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  helper_method :users

  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :user_is_admin, only:[:index, :edit, :update]

  def index
    @title = "Список пользователей"
    @users = User.all
  end

  def show
    @title = "Профиль пользователя"
    @user = User.find(params[:id])
  end

  def new
    @title = "Создать пользователя"
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
        create_user_role
        redirect_to users_path
    else

      @title = "Создать пользователя"
      render 'new'

    end
  end

  def edit
    @title = "Редактирование пользователя"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      @user.skip_password_validation = true
      cur_params = user_params_without_pass
    else
      cur_params = user_params
    end

    if @user.update_attributes(cur_params)
      update_user_role
      flash[:success] = "Данные пользователя обновлены"
      redirect_to @user
    else
      @title = "Редактирование пользователя"
      render 'edit'
    end

  end

  def destroy
    user = User.find(params[:id])
    user_role = UsersRole.find_by(user:user)
    user.destroy
    user_role.destroy

    flash[:success] = "Пользователь удален"
    redirect_to users_path
  end

  def ajax_uzel

    client = Savon_client::CLIENT
    response = client.call(:get_client, message: {ИНН:params[:inn], КПП:params[:kpp]})

    if response.body[:fault].present?
      @response = {status:"error",message:response.body[:fault][:reason][:text]}
    else
      @response = {status:"ok", message:"", data:response.body[:get_client_response][:return]}
    end

    render json: @response

  end


  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Для выполнения этого действия нужна авторизация"
      end
    end

    def user_is_admin
      unless current_user.is_admin?
        redirect_to signin_url, notice: "Войдите как администратор"
      end
    end

    def users
      @users ||= User.all
    end

    def create_user_role
      @role = Role.find_by_name params[:user][:roles]
      UsersRole.create user:@user, role:@role
    end

    def update_user_role
      role = Role.find_by_name params[:user][:roles]
      user_role = UsersRole.find_by(user:@user)
      user_role.update_attribute(:role, role)
    end

    def user_params_without_pass
      params.require(:user).permit(:name, :email, :active)
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :active)
    end

end

app/helpers/users_helper.rb
module UsersHelper


  def fetch_agent_data( user )

    response = soap_response

    #binding.pry

    if response.present? && response.body[:fault].blank? && response.http.code == 200

      @tarifs = response.body[:get_tarifs_response][:return][:Тариф]


      @tarifs.each do |tarif|

        t = Tarif.find_or_create_by(type_t:tarif[:ТипТарифа], platform:tarif[:Площадка])

        t.update  type_t:               tarif[:ТипТарифа],
                  platform:             tarif[:Площадка],
                  rate:                 tarif[:Ставка],
                  dop_rate:             tarif[:СтавкаДополнительная],
                  client_rate:          tarif[:СтавкаКонечника],
                  minimum:              tarif[:Минималка],
                  personal_number_flag: tarif[:ЕстьЛицевойСчет],
                  client_dop_rate:      tarif[:СтавкаКонечникаДополнительная]

      end

        true

    else

        false

    end

  end

  def soap_response
    begin
      Savon_client::CLIENT.call(:get_tarifs)
    rescue (Timeout::Error || Errno::ECONNRESET) => e
      puts "-- #{e} --"
    end
  end

end

app/views/users/edit.html.haml
.form-wrap
  = simple_form_for @user, validation: true do |f|
    .field
      %label Имя
      = f.input_field :name
      = f.error :name
    .field
      %label Email
      = f.input_field :email
      = f.error :email
    .field
      %label Активность
      = f.input_field :active
    .field
      %label Роль
      = f.select(:roles, Role.all.reverse.map {|role| [role.title, role.name]}, selected: @user.roles.first.name)
    .field
      %label Пароль
      = f.password_field :password, value:""
      = f.error :password
    .field
      %label Повторите пароль
      = f.password_field :password_confirmation
      = f.error :password_confirmation
    .field.submit
      = f.button :submit, value: "Обновить", class:"btn-success"

app/views/users/index.html.haml
%table.simple-list
  %thead
    %tr
      %th Логин
      %th Email
      %th Роль
      %th Активность
      %th Последний вход
      %th
      %th
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= user.roles.first.title
          %td
            - if user.active
              активен
            - else
              неактивен
          %td= user.last_visit.to_formatted_s(:long) if user.last_visit
          %td.edit
            = link_to "изменить", edit_user_path(user)
          - unless user.is_admin?
            %td.del
              = link_to "удалить", user, method: :delete, data:{confirm:"Удалить пользователя?"}
- if current_user && current_user.is_admin?
  %div.add-user= link_to "Добавить пользователя", users_new_path

app/views/users/new.html.haml
.form-wrap
  = simple_form_for @user, validation: true do |f|
    .field
      %label Имя
      = f.input_field :name
      = f.error :name
    .field
      %label Email
      = f.input_field :email
      = f.error :email
    .field
      %label Активность
      = f.input_field :active
    .field
      %label Роль
      = f.select(:roles, Role.all.reverse.map {|role| [role.title, role.name]})
    .field
      %label Пароль
      = f.input_field :password
      = f.error :password
    .field
      %label Повторите пароль
      = f.input_field :password_confirmation
      = f.error :password_confirmation
    .field.submit
      = f.button :submit, value: "Создать", class:"btn-success"

app/views/users/show.html.haml
%h1= @user.name
%p= @user.email