config/routes.rb
Rails.application.routes.draw do

  get 'reports/fetch_report'

  resources :orders


  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'

  resources :users

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/uzel', to:"users#ajax_uzel",          via: 'post'



  resources :sessions, only: [:new, :create, :destroy]


  resources :reports

  match '/report', to:"reports#fetch_report",   via: 'post'

  root 'orders#index'

end

app/models/order.rb
class Order < ActiveRecord::Base


  attr_accessor :skip_validation

  has_one :borrower, ->{ where attachable_type: 'borrower'}, class_name: 'Organization', dependent: :destroy

  has_many :guarantor_legals, ->{ where attachable_type: 'guarantor_legal'}, class_name: 'Organization', dependent: :destroy
  has_many :guarantor_individuals, class_name: 'Individual', dependent: :destroy
  has_many :documents, dependent: :destroy


  accepts_nested_attributes_for :borrower, allow_destroy: true

  accepts_nested_attributes_for :guarantor_legals, allow_destroy: true
  accepts_nested_attributes_for :guarantor_individuals, allow_destroy: true
  accepts_nested_attributes_for :documents, allow_destroy: true

  validates_associated :borrower
  validates_associated :guarantor_legals
  validates_associated :guarantor_legals


  validates :summa, presence: true, numericality: {greater_than: 0}
  validates :platform, presence: true
  validates :submission_deadline, presence: true, unless: :skip_validation
  validates :agent, presence: true
  validates :create_date, presence: true

  #validates :agent_name, presence: true
  #validates :agent_summa, presence: true
  #validates :mfo_summa, presence: true
  #validates :dogovor_summa, presence: true
  #validates :tarif, presence: true
  #validates :number
  #validates :number_mfo
  #validates :number_data_protocol
  #validates :personal_number

  #validates :status, presence: true

  validates_presence_of :documents, unless: :skip_validation

end

app/helpers/order_helper.rb
module OrderHelper

  def send_mfo(order)

    require 'base64'

    savon_client = Savon_client::CLIENT

    @operations = savon_client.operations

    if @operations.include? :send_data

    # @order.МассивАнкет

      order_raw = { МассивАнкет: [ АнкетаЗаявка: {
                  Дата:  format_date_for_datetime( DateTime.now ),
                  Номер: "",
                  Агент: order.agent,
                  АгентНаименование: order.agent_name,
                  СуммаВознагражденияАгента: order.agent_summa,
                  СтатусСделки: "На заполнении",
                  КрайнийСрокПредоставления: format_date_for_datetime(order.submission_deadline),
                  НомерМФО: nil,
                  НомерДатаПротокола: order.number_data_protocol,
                  СуммаГарантийногоВзноса: order.dogovor_summa,
                  СуммаЗайма: order.summa,
                  ЭлектроннаяПлощадка: order.platform,
                  Тариф: order.tarif,
                  ПредметКонтракта: order.contract_subject,
                  НомерЛота: order.lot_number,
                  ЛицевойСчет: order.personal_number,
                  НомерЗаявкиММВБ: order.number_mmvb,
                  Заемщик:{
                            Тип: order.borrower.type_o,
                            Наименование: order.borrower.name,
                            ПолноеНаименование: order.borrower.fullname,
                            ИНН:order.borrower.inn,
                            КПП: order.borrower.kpp,
                            ОГРН: order.borrower.ogrn,
                            ОсновнойБанковскийСчет:{
                                БИК:order.borrower.bank_account.bank.bik,
                                НомерСчета: order.borrower.bank_account.account_number,
                                БанкНаименование: order.borrower.bank_account.bank.name,
                                КоррСчет:order.borrower.bank_account.bank.korr_number,
                                ИНН:order.borrower.bank_account.bank.inn,
                            },
                            ЮридическийАдрес:{
                                ПочтовыйИндекс:order.borrower.address_legal.indx,
                                Регион:order.borrower.address_legal.region,
                                Район:order.borrower.address_legal.raion,
                                НаселенныйПункт:order.borrower.address_legal.punkt,
                                Улица:order.borrower.address_legal.street_name,
                                КодУлицы:order.borrower.address_legal.street_code,
                                НомерДома:order.borrower.address_legal.house,
                                Корпус:order.borrower.address_legal.corps,
                                Строение:order.borrower.address_legal.building,
                                НомерКвартиры:order.borrower.address_legal.apart_number
                            },
                            ФактическийАдрес:{
                                ПочтовыйИндекс:order.borrower.address_actual.indx,
                                Регион:order.borrower.address_actual.region,
                                Район:order.borrower.address_actual.raion,
                                НаселенныйПункт:order.borrower.address_actual.punkt,
                                Улица:order.borrower.address_actual.street_name,
                                КодУлицы:order.borrower.address_actual.street_code,
                                НомерДома:order.borrower.address_actual.house,
                                Корпус:order.borrower.address_actual.corps,
                                Строение:order.borrower.address_actual.building,
                                НомерКвартиры:order.borrower.address_actual.apart_number
                            },
                            ДолжностьРуководителя:order.borrower.head_position,
                            ДатаГосРегистрации:format_date_for_datetime(order.borrower.reg_date),
                            Телефон:order.borrower.phone,
                            EMail: order.borrower.email,
                            ПерсональныеДанныеЗаявителя:{
                                ФИО: order.borrower.person.fullname,
                                ДатаРождения: format_date_for_datetime(order.borrower.person.birthday),
                                СерияНомерПаспорта: order.borrower.person.pass_serial_number,
                                ДатаВыдачи: format_date_for_datetime(order.borrower.person.pass_issue_date),
                                КемВыдан: order.borrower.person.pass_issued,
                                КодПодразделения: order.borrower.person.pass_issued_code,
                                МестоРождения: order.borrower.person.birth_place,
                                Гражданство:order.borrower.person.citizenship,
                                АдресРегистрации:{
                                    ПочтовыйИндекс:order.borrower.person.reg_place.indx,
                                    Регион:order.borrower.person.reg_place.region,
                                    Район:order.borrower.person.reg_place.raion,
                                    НаселенныйПункт:order.borrower.person.reg_place.punkt,
                                    Улица:order.borrower.person.reg_place.street_name,
                                    КодУлицы:order.borrower.person.reg_place.street_code,
                                    НомерДома:order.borrower.person.reg_place.house,
                                    Корпус:order.borrower.person.reg_place.corps,
                                    Строение:order.borrower.person.reg_place.building,
                                    НомерКвартиры:order.borrower.person.reg_place.apart_number
                                },
                                АдресМестаПребывания:{
                                    ПочтовыйИндекс:order.borrower.person.curr_place.indx,
                                    Регион:order.borrower.person.curr_place.region,
                                    Район:order.borrower.person.curr_place.raion,
                                    НаселенныйПункт:order.borrower.person.curr_place.punkt,
                                    Улица:order.borrower.person.curr_place.street_name,
                                    КодУлицы:order.borrower.person.curr_place.street_code,
                                    НомерДома:order.borrower.person.curr_place.house,
                                    Корпус:order.borrower.person.curr_place.corps,
                                    Строение:order.borrower.person.curr_place.building,
                                    НомерКвартиры:order.borrower.person.curr_place.apart_number
                                },
                                Телефон:order.borrower.person.phone,
                                ЭлектроннаяПочта:order.borrower.person.email,
                                СерияНомерСП:order.borrower.person.old_pass_serial_number,
                                ДатаВыдачиСП: format_date_for_datetime(order.borrower.person.old_pass_issue_date) ,
                                КемВыданСП: order.borrower.person.old_pass_issued,
                                КодПодразделенияСП: order.borrower.person.old_pass_issued_code,
                            },
                            Учередители:[]

                          },
                  ПоручительЮЛ:nil,
                  ПоручительФЛ:nil,
                  ДокументыИсполнителя:[]

                }]
      }

      if order.borrower.borrower_founders.any?
        order.borrower.borrower_founders.each_with_index do |bf, index|
          order_raw[:МассивАнкет][0][:АнкетаЗаявка][:Заемщик][:Учередители] << {
              УчередительНаименование: bf.name,
              Доля: bf.share,
              ПаспортныеДанныеОГРН: bf.pass_data_ogrn
          }
        end
      end

      if order.guarantor_individuals[0].present?
        order_raw[:МассивАнкет][0][:АнкетаЗаявка][:ПоручительФЛ] = {
            ФИО: order.guarantor_individuals[0].fullname,
            ДатаРождения: format_date_for_datetime(order.guarantor_individuals[0].birthday),
            СерияНомерПаспорта: order.guarantor_individuals[0].pass_serial_number,
            ДатаВыдачи: format_date_for_datetime(order.guarantor_individuals[0].pass_issue_date),
            КемВыдан: order.guarantor_individuals[0].pass_issued,
            КодПодразделения: order.guarantor_individuals[0].pass_issued_code,
            МестоРождения: order.guarantor_individuals[0].birth_place,
            Гражданство:order.guarantor_individuals[0].citizenship,
            АдресРегистрации:{
                ПочтовыйИндекс:order.guarantor_individuals[0].reg_place.indx,
                Регион:order.guarantor_individuals[0].reg_place.region,
                Район:order.guarantor_individuals[0].reg_place.raion,
                НаселенныйПункт:order.guarantor_individuals[0].reg_place.punkt,
                Улица:order.guarantor_individuals[0].reg_place.street_name,
                КодУлицы:order.guarantor_individuals[0].reg_place.street_code,
                НомерДома:order.guarantor_individuals[0].reg_place.house,
                Корпус:order.guarantor_individuals[0].reg_place.corps,
                Строение:order.guarantor_individuals[0].reg_place.building,
                НомерКвартиры:order.guarantor_individuals[0].reg_place.apart_number
            },

            АдресМестаПребывания:{
                ПочтовыйИндекс:order.guarantor_individuals[0].curr_place.indx,
                Регион:order.guarantor_individuals[0].curr_place.region,
                Район:order.guarantor_individuals[0].curr_place.raion,
                НаселенныйПункт:order.guarantor_individuals[0].curr_place.punkt,
                Улица:order.guarantor_individuals[0].curr_place.street_name,
                КодУлицы:order.guarantor_individuals[0].curr_place.street_code,

app/views/orders/edit.html.haml
= render partial: 'shared/order_menu'
- @active_tab = params[:service] && params[:service][:edit_order_active_tab] ? params[:service][:edit_order_active_tab] : 'calc'
.order-form.edit
  %ul.nav.nav-tabs{id:"order-tabs"}
    - if session[:editkey].blank?
      - if current_user.present? && (current_user.is_admin? || current_user.is_agent? || current_user.is_client?)
        %li{class:"#{'active' if @active_tab == 'calc'}"}
          %a{href:"#calc", data:{toggle:"tab"}} Калькулятор
          %span.badge.fade
    %li{class:"#{'active' if @active_tab == 'loan'}"}
      %a{href:"#loan", data:{toggle:"tab"}} Займ
      %span.badge.fade
    %li{class:"#{'active' if @active_tab == 'borrower'}"}
      %a{href:"#borrower", data:{toggle:"tab"}} Заемщик
      %span.badge.fade
    %li{class:"#{'active' if @active_tab == 'guarantors'}"}
      %a{href:"#guarantors", data:{toggle:"tab"}} Поручители
      %span.badge.fade
    %li{class:"#{'active' if @active_tab == 'documents'}"}
      %a{href:"#documents", data:{toggle:"tab"}} Прикрепленные документы
      %span.badge.fade



  = simple_form_for @order, html:{multipart:true}, validation: true do |f|
    .tab-content{id:"tabs"}

      -# КАЛЬКУЛЯТОР #
      - if session[:editkey].blank?
        - if current_user.present? && (current_user.is_admin? || current_user.is_agent? || current_user.is_client?)
          .tab-pane.fade{id:"calc", class:"#{' in active' if @active_tab == 'calc'}", data:{type:"#{current_user.roles.first.name}"}}
            = render partial: 'shared/platform_tarif', locals: {f:f}
            = render partial: 'shared/calcs', locals:{f:f}


      -# ЗАЯВКА #
      .tab-pane.fade{id:"loan", class:"#{' in active' if @active_tab == 'loan'}"}
        .field-group
          .field
            %label Площадка
            -#= f.select(:platform, Tarif.uniq.pluck(:platform).map {|platform| [platform, platform, data:{number:platform}]})
            = f.input_field :platform, readonly: true
            = f.error :platform
          .field.hidden
            %label Тариф
            = f.input_field :tarif
            = f.error :tarif
          .field.hidden
            %label Ставка
            = f.input_field :base_rate
            = f.error :base_rate
          .field
            %label Сумма
            = f.input_field :summa, readonly: true
            = f.error :summa
          .field
            %label Крайний срок предоставления
            = f.date_field :submission_deadline
            = f.error :submission_deadline

          .field
            %label Предмет контракта
            = f.input_field :contract_subject
            = f.error :contract_subject
          .field
            %label Номер лота
            = f.input_field :lot_number
            = f.error :lot_number
          .field#personal-number
            %label Номер лицевого счета
            = f.input_field :personal_number
            = f.error :personal_number
          .field.hidden#number-mmvb
            %label Номер заявки ММВБ
            = f.input_field :number_mmvb
            = f.error :number_mmvb

          .field.hidden
            %label Агент
            = f.input_field :agent
            = f.error :agent
          .field.hidden
            %label АгентНаименование
            = f.input_field :agent_name
            = f.error :agent_name
          .field.hidden
            %label АгентВознаграждение
            = f.input_field :agent_summa
            = f.error :agent_summa
          .field.hidden
            %label МфоВознаграждение
            = f.input_field :mfo_summa
            = f.error :mfo_summa
          .field.hidden
            %label ДоговорВознаграждение
            = f.input_field :dogovor_summa
            = f.error :dogovor_summa
          .field.hidden
            %label Номер
            = f.input_field :number
            = f.error :number
          .field.hidden
            %label НомерМФО
            = f.input_field :number_mfo
            = f.error :number_mfo
          .field.hidden
            %label НомерДатаПротокола
            = f.input_field :number_data_protocol
            = f.error :number_data_protocol
          .field.hidden
            %label Дата создания
            = f.date_field :create_date, value: f.object.create_date || Date.today
            = f.error :create_date
          .field.hidden
            %label Статус
            = f.input_field :status
            = f.error :status


      -# ОРГАНИЗАЦИЯ - ЗАЕМЩИК #

      .tab-pane.fade{id:"borrower", class:"#{' in active' if @active_tab == 'borrower'}"}
        = f.fields_for :borrower do |b|
          .field-group
            .field
              %label Укажите тип заемщика
              = b.select :type_o, [['Выберите тип заемщика', ''],['Юридическое лицо', 'ЮЛ'] ,['Индивидуальный предприниматель', 'ФЛ']]
              = b.error :type_o

          .field-group
            .field-horizontal
              .field.inn
                %label ИНН
                = b.input_field :inn
                = b.error :inn
              .field{class:"kpp #{'hidden' if @order.borrower.type_o == 'ФЛ'}"}
                %label КПП
                = b.input_field :kpp
                = b.error :kpp
            .field.button-right
              .indicator.hidden{id:'borrower-indicator'}
              %button.btn.btn-primary.check{type:'button',data:{targetform:'check-borrower'}} Искать в базе

          .field-group
            %h5.title Основные данные
            .field.long
              %label Название организации
              = b.input_field :name
              = b.error :name
            .field.long
              %label Полное название организации
              = b.input_field :fullname
              = b.error :fullname
            .field-horizontal
              .field
                %label Дата регистрации
                = b.date_field :reg_date
                = b.error :reg_date
              .field
                %label ОГРН
                = b.input_field :ogrn
                = b.error :ogrn
            .field-horizontal
              .field
                %label Должность руководителя
                = b.input_field :head_position
                = b.error :head_position
              .field
                %label Телефон
                = b.input_field :phone
                = b.error :phone
            .field
              %label Email
              = b.input_field :email
              = b.error :email

            .sub-group
              %h5.title Юридический адрес
              = b.fields_for :address_legal do |al|
                = render partial: 'shared/address', locals: {a:al}

            .sub-group
              %h5.title Фактический адрес
              = b.fields_for :address_actual do |aa|
                = render partial: 'shared/address', locals: {a:aa}


          .field-group.borrower-founders{class:"#{' hidden' if @order.borrower.type_o == 'ФЛ'}"}
            = render partial:'shared/founders', locals: {b:b}

          .field-group
            %h5.title Основной банковский счет

            = b.fields_for :bank_account do |ba|
              .field-horizontal
                .field
                  %label Номер счета
                  = ba.input_field :account_number
                  = ba.error :account_number

                = ba.fields_for :bank do |bank|
                  .field
                    %label Бик
                    = bank.input_field :bik
                    = bank.error :bik
                  .field-horizontal
                    .field
                      %label Коррсчет
                      = bank.input_field :korr_number
                      = bank.error :korr_number
                    .field
                      %label ИНН
                      = bank.input_field :inn
                      = bank.error :inn
                  .field-horizontal
                    .field
                      %label Наименование банка
                      = bank.input_field :name
                      = bank.error :name
                    .field
                      %label Город
                      = bank.input_field :city
                      = bank.error :city
                  .field.long
                    %label Адрес
                    = bank.input_field :address
                    = bank.error :address

          .field-group.personal-data{class:"#{' hidden' if @order.borrower.type_o == 'ФЛ'}"}
            %h5.title Персональные данные заемщика

            = b.fields_for :person do |p|
              .field-horizontal
                .field
                  %label ФИО
                  = p.input_field :fullname
                  = p.error :fullname
                .field
                  %label Дата рождения
                  = p.date_field :birthday
                  = p.error :birthday
              .field-horizontal
                .field
                  %label Место рождения
                  = p.input_field :birth_place
                  = p.error :birth_place
                .field
                  %label Гражданство
                  = p.input_field :citizenship, value:"РФ"
                  = p.error :citizenship
              .field-horizontal
                .field
                  %label Телефон
                  = p.input_field :phone
                  = p.error :phone
                .field
                  %label E-mail
                  = p.input_field :email
                  = p.error :email

              .sub-group
                %h5.title Место регистрации
                = p.fields_for :reg_place do |rp|
                  = render partial: 'shared/address', locals: {a:rp}

              .sub-group
                %h5.title Место пребывания
                = p.fields_for :curr_place do |cp|
                  = render partial: 'shared/address', locals: {a:cp}


              .sub-group
                %h5.title Паспортные данные

                .field
                  %label Серия и номер паспорта
                  = p.input_field :pass_serial_number
                  = p.error :pass_serial_number

                .field.long
                  %label Кем выдан
                  = p.input_field :pass_issued
                  = p.error :pass_issued
                .field-horizontal
                  .field
                    %label Код подразделения
                    = p.input_field :pass_issued_code
                    = p.error :pass_issued_code

                  .field
                    %label Дата выдачи
                    = p.date_field :pass_issue_date
                    = p.error :pass_issue_date



                .sub-group
                  %h5.title Данные о ранее выданных паспортах

                  .field
                    %label Серия и номер паспорта
                    = p.input_field :old_pass_serial_number
                    = p.error :old_pass_serial_number

                  .field.long
                    %label Кем выдан
                    = p.input_field :old_pass_issued
                    = p.error :old_pass_issued
                  .field-horizontal
                    .field
                      %label Код подразделения
                      = p.input_field :old_pass_issued_code
                      = p.error :old_pass_issued_code

                    .field
                      %label Дата выдачи
                      = p.date_field :old_pass_issue_date
                      = p.error :old_pass_issue_date

      -# ПОРУЧИТЕЛИ #

      .tab-pane.fade{id:"guarantors", class:"#{' in active' if @active_tab == 'guarantors'}"}
        = simple_fields_for :service do |s|
          .field.radio-group
            %label Выберите тип поручителя
            = s.collection_radio_buttons :guarantor_type, [['guarantor_individual', 'Физическое лицо'], ['guarantor_legal', 'Юридическое лицо']], :first, :last,
            checked: params[:service] ? params[:service][:guarantor_type] : 'guarantor_individual'

        -# ПОРУЧИТЕЛИ ФИЗИЧЕСКОЕ ЛИЦО #
        - @hidden = params[:service] ? params[:service][:guarantor_type] == 'guarantor_legal' : false

        .guarantor{class:"guarantor_individual #{'hidden' if @hidden}"}
          = render partial: 'shared/guarantor_individual_edit', locals: {f:f}

        -# ПОРУЧИТЕЛЬ ЮРИДИЧЕСКОЕ ЛИЦО #
        - @hidden = params[:service] ? params[:service][:guarantor_type] == 'guarantor_individual' : true

        .guarantor{class:"guarantor_legal #{ 'hidden' if @hidden}"}
          = render partial: 'shared/guarantor_legal_edit', locals:{f:f}


      .tab-pane.fade{ id:"documents", class:"#{' in active' if @active_tab == 'documents'}"}
        = render partial: 'shared/order_documents', locals:{f:f}

      - if !current_user.is_client?
        .field-submit
          = simple_fields_for :service do |s|
            = s.hidden_field :send_mfo, value: false
            = s.hidden_field :edit_order_active_tab, value: params[:service] && params[:service][:edit_order_active_tab] ? params[:service][:edit_order_active_tab] : ""

          -# title = (session[:editkey].blank? || (current_user.present? && (current_user.is_admin? || current_user.is_agent?))) ? 'Сформировать ссылку' : 'Сохранить'
          = submit_tag 'Сохранить', class:'btn btn-primary'


%script
  window.tarifs =
  =raw @tarifs.to_json

app/views/orders/guest_index.html.haml
= link_to "Редактировать заявку", edit_order_path + "?" + session[:editkey]

app/views/orders/index.html.haml
- if @orders.any?
  %table.simple-list.orders
    %caption Заявки на редактировании
    %thead
      %tr
        %th Дата создания
        %th Дата обновления
        %th Платформа
        %th ИНН
        %th Сумма займа

        - unless current_user.is_client?
          %th Сумма договора
        - else
          %th Стоимость

        - unless current_user.is_client?
          %th Сумма МФО
          %th Сумма агента
        %th Статус
        - unless current_user.is_client?
          %th Ссылка для клиента

        %th &nbsp;
        %th &nbsp;
    %tbody
      - @orders.each do |order|
        %tr{class:"#{'in-mfo' if order.status == "Отправлено в МФО"}"}
          %td.date
            = order.created_at.to_formatted_s(:long)
          %td.date
            = order.updated_at.to_formatted_s(:long)
          %td
            = order.platform
          %td
            = order.borrower.inn
          %td
            = order.summa
          %td
            = order.dogovor_summa
          - unless current_user.is_client?
            %td
              = order.mfo_summa
            %td
              = order.agent_summa
          %td.status
            = order.status
          - unless current_user.is_client?
            %td
              = "#{request.protocol}#{request.host}#{orders_path}/#{order.id.to_s}/edit?#{order.editkey}"
          %td.edit
            - if order.status != "Отправлено в МФО"
              = link_to "Изменить", edit_order_path(order)
          %td.del
            = link_to "Удалить", order, method: :delete, data: {confirm: "Удалить заявку?"}
- else
  %h4 Нет заявок на заполнении


.fetch-orders-form.text-right
  = form_tag "/report", method: :post, id: "fetch-orders-form", remote:true do |f|
    .indicator{id:"report-indicator"} получаем заявки
    = hidden_field_tag 'shift[date_from]', "1970-01-01"
    = hidden_field_tag 'shift[date_to]', Date.today
    = hidden_field_tag :authenticity_token
    .field-horizontal.order-filter
      -#= submit_tag "Обновить список", class:'btn btn-success hidden'
      = select_tag "order-status", options_for_select(["на заполнении","оформление", "согласование","к выдаче", "выдан", "закрыт", "отклонена", "отказ клиента"]), prompt: "Отфильтруйте по статусу", class: 'hidden'
%table.fade.simple-list{id:"orders-list"}
  %caption Отправленные заявки
  %thead
    %tr
      %th
      %th Дата создания
      %th Дата выдачи
      %th Заемщик
      %th Сумма займа
      %th Сумма агента
      %th Статус
  %tbody

%script
  window.tarifs =
  =raw @tarifs.to_json