config/routes.rb
Rails.application.routes.draw do

  get 'reports/fetch_report'

  resources :orders


  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/edit'

  resources :users

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/uzel', to:"users#ajax_uzel",          via: 'post'



  resources :sessions, only: [:new, :create, :destroy]


  resources :reports

  match '/report', to:"reports#fetch_report",   via: 'post'

  root 'orders#index'

end

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-md-6
        %span= debug(params) if Rails.env.development?
      .col-md-6.text-right
        %span
          &copy; ООО «МФО Альянс»

%aside.ajax-form-block.hidden
  = form_tag "/uzel", data:{formtype:"check-borrower"}, remote:true do
    = hidden_field_tag :authenticity_token
    = hidden_field_tag :action, "get-client"
    = text_field_tag :inn, ""
    = text_field_tag :kpp, ""

%div.modal.fade.bs-example-modal-sm{id:"founder-message",tabindex:"-1",role:"dialog",aria:{labelledby:"mySmallModalLabel",hidden:"true"}}
  %div.modal-dialog.modal-sm
    %div.modal-content
      %div.modal-header
        %button.close{type:"button",data:{dismiss:"modal"},aria:{hidden:"true"}} &times;
        %h4.modal-title Сообщение
      %div.modal-body
        Должен быть хотя бы один учредитель!

app/views/layouts/_header.html.haml
%header
  .container
    %a.logo{href:orders_path}
      %img{src:image_url('logo.png')}

    %nav.main-menu
      %ul
        - if signed_in? && current_user
          %li= link_to "Новая заявка", new_order_path, :class => is_active?('orders/new')
          %li= link_to "История заявок", orders_path, :class =>is_active?('orders/index')

          - if current_user.is_admin? || current_user.is_agent?
            %li= link_to "Отчеты", reports_path, :class =>is_active?('reports/index')

        - if signed_in? && current_user && current_user.is_admin?
          %li= link_to "Пользователи", users_path, :class => is_active?('users/index')

        - if signed_in?
          %li= link_to "Выход", signout_path, method: "delete"
        - else
          %li= link_to "Вход", signin_path

    - if signed_in? && current_user
      %div.user-info
        %span пользователь:
        %span.login
          = current_user.email
        %span.role (#{current_user.roles.first.title.mb_chars.downcase})

    %h1.page-title= @title;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %title Mfo
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .page-wrap
      = render 'layouts/header'
      %main
        .container
          - flash.each do |key, value|
            %div{class:"alert alert-#{key}"}= value.html_safe

          = yield
    = render 'layouts/footer'
    -#- if signed_in?
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//cdn.jsdelivr.net/webshim/1.14.5/polyfiller.js"
    %script
      webshims.setOptions('waitReady', false);
      webshims.setOptions('forms-ext', {types: 'date'});
      webshims.cfg.no$ = true
      webshims.polyfill('forms forms-ext');